const channelUrls = [
    "https://www.youtube.com/channel/UCpryVRk_VDudG8SHXgWcG0w",
    "https://www.youtube.com/channel/UCU2PacFf99vhb3hNiYDmxww",
    "https://www.youtube.com/channel/UC9LQwHZoucFT94I2h6JOcjw",
    "https://www.youtube.com/channel/cUCkzCjdRMrW2vXLx8mvPVLdQ",
    "https://www.youtube.com/channel/UC6yW44UGJJBvYTlfC7CRg2Q",
    "https://www.youtube.com/channel/UCEg25rdRZXg32iwai6N6l0w",
    "https://www.youtube.com/channel/UCICNP0mvtr0prFwGUQIABfQ",
    "https://www.youtube.com/channel/UCeOCuVSSweaEj6oVtJZEKQw",
    "https://www.youtube.com/channel/UCAalMUm3LIf504ItA3rqfug",
    "https://www.youtube.com/channel/UCf-cpC9WAdOsas19JHipukA",
    "https://www.youtube.com/channel/UCWB9N0012fG6bGyj486Qxmg",
    "https://www.youtube.com/channel/UCtK4QAczAN2mt2ow_jlGinQ",
    "https://www.youtube.com/channel/UC2VLfz92cTT8jHIFOecC-LA",
    "https://www.youtube.com/channel/UCyQcJHDN4uYfPa1DHzKVSnw",
    "https://www.youtube.com/channel/UCBkRQtxofyXr09mWtgoUUqw",
    "https://www.youtube.com/channel/UCywGl_BPp9QhD0uAcP2HsJw",
    "https://www.youtube.com/channel/UCyAxjuAr8f_BFDGCO3Htbxw",
    "https://www.youtube.com/channel/UCxvXjfiIHQ2O6saVx_ZFqnw",
    "https://m.youtube.com/channel/UCCNOsmurvpEit9paBOzWtUg",
    "https://www.youtube.com/channel/UCQ7Lqg5Czh5djGK6iOG53KQ"
  ];
  module.exports={channelUrls}